language: node_js
node_js:
- 14
install:
- npm install
script:
- npm run test
deploy:
  provider: npm
  email: sebastian.lzy@gmail.com
  api_key:
    secure: BjE6Kqz3KydcrE4ZLYEwACd0GEs+N1EHRS42ghQySRmO1zxBxAtI7nLIRVG8zbsURzwElRvAfdJeAN3pN2kbdkfJtquPcyScnzN0+CgFXtTTCrIycXR5hmySMkqxxdYfO/YMiX2c1WJfliBFy8NxxE15hfv4PLpO6DFyhk9oMwH6cjEwpm+uQxbb9yAYhVNRUzlnFAm+6jdcQJ0D+7fhh2jv9eJTWzBQDbTYNWgS4Tq/Lfl89e5DigFCWsgX7W19WoabfATcbLOpISuhThLqtT99iedeSnKG57POH/4ShtJmzGZdh5iMS0XnbJcESTzvGuvAKnj1vNEUWxo5/9Qu5xFmYCU4GKrD7UX1pZIKAMdPmYWaUQpZJVau4Get4YUuF6NHdZu++Nodp8WUDV9OxBJMze02la+Bs1TbK4UXmN9Y0co1uHw7GIyGp3PhSTm9zJQGDKUg2/Wn3191+tda5e2iAYjylzhf25bYSkboy8Gn9Nm0KX6EvATrDm7TL8X7lY6Mnl7H7RHC/9kYEX5OWXq4m7iSYY35+wG5REqL9jAdtOt4VQGxPeel2LXRqkZKRwSPws8EfVX7WBKpyd3SwHIlxn1DljwW+NaGJ+ig59zPVwJoVcrnRVnGW0pjELp30/6s4eDhhq6r78EHWOXM/Rt3uiugV8KwMf5rN6WgLUg=
  on:
    tags: true
    repo: sebastianlzy/upload-file-to-s3
    branch: main
  skip_cleanup: 'true'
